version: '3'

networks:
  net: { name: "socks5-openvpn", driver: bridge, external: false }

services:
  socks5-openvpn:
    image: socks5-proxy:dev
    restart: always
    cap_add: [NET_ADMIN]
    devices: [/dev/net/tun:/dev/net/tun]
    networks: ["net"]
    ports: ["127.0.0.1:1070:1070", "127.0.0.1:1090:1090"]
    container_name: socks5-openvpn
    volumes:
    - ./configs/:/apps/configs:ro
    - ./site/:/apps/site
    - ./logs/:/apps/logs
    environment: ["TZ=Asia/Shanghai"]
    working_dir: /apps
    command:
    - "supervisord"
    - "-l"
    - "logs/supervisord.log"
    - "-c"
    - "configs/supervisord.conf"
