app_name: socks5-proxy
app_version: 1.0.1
authors: ["d2jvkpn <d2jvkpn@noreply.local>"]
repository: git@github.com:d2jvkpn/socks5-proxy.git
image_name: socks5-proxy

socks5_ssh: |
  # path: configs/local.yaml

  ssh:
    ssh_host: remote_host
    ssh_port: 22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts
    socks5_user: hello
    socks5_password: world

  noauth:
    ssh_host: remote_host
    ssh_port: 22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts

supervisor_vpn: |
    # path: /apps/configs/supervisor.ini

    [program:openvpn]
    user=root
    # --auth-user-pass configs/openvpn.ovpn.auth (account\npassword)
    command=openvpn --config configs/openvpn.ovpn --auth-nocache --askpass configs/openvpn.ovpn.pass
    autostart=true
    autorestart=true
    stdout_logfile=logs/openvpn.log
    stderr_logfile=logs/openvpn.error

    [program:socks5_server]
    command=target/main server --addr=:1090
    autostart=true
    autorestart=true
    stdout_logfile=logs/socks5_server.log
    stderr_logfile=logs/socks5_server.error

    [program:file_server]
    command=target/main file_server --addr=:1099
    autostart=true
    autorestart=true
    stdout_logfile=logs/file_server.log
    stderr_logfile=logs/file_server.error

supervisor_ssh: |
    # path: /apps/configs/supervisor.ini

    [program:socks5_ssh]
    command=target/main, ssh, -config=configs/prod.yaml, -addr=127.0.0.1:1080
    autostart=true
    autorestart=true
    stdout_logfile=logs/socks5_ssh.log
    stderr_logfile=logs/socks5_ssh.error

    [program:file_server]
    command=target/main file_server --addr=:1089
    autostart=true
    autorestart=true
    stdout_logfile=logs/file_server.log
    stderr_logfile=logs/file_server.error

ssh_config: |
    # path: configs/ssh.conf

    Host remote_host
        # ProxyJump host01,host02
        # ProxyCommand  nc -X 5 -x 127.0.0.1:1090 %h
        HostName 127.0.0.1
        User account
        Port 22
        IdentityFile configs/account.ssh-ed25519 # ~/.ssh/id_rsa
        UserKnownHostsFile configs/ssh-known_hosts # ~/.ssh/known_hosts
        LogLevel    INFO
        Compression yes
        ServerAliveInterval 5
        ServerAliveCountMax 3
        ExitOnForwardFailure yes
