app_name: socks5-proxy
app_version: 1.0.2
authors: ["d2jvkpn <d2jvkpn@noreply.local>"]
repository: git@github.com:d2jvkpn/socks5-proxy.git
image_name: socks5-proxy

socks5_ssh: |
  # path: configs/local.yaml

  ssh:
    ssh_host: remote_host
    ssh_port: 22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts
    socks5_user: hello
    socks5_password: world

  noauth:
    ssh_host: remote_host
    ssh_port: 22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts

supervisor_openvpn: |
    # path: /apps/configs/supervisor.ini

    # to enable inet_http_server, copy and edit the following lines to /apps/configs/supervisor.ini
    ;[inet_http_server]    # inet (TCP) server disabled by default
    ;port=:1098            # (ip_address:port specifier, *:port for all iface)
    ;username=user         # (default is no username)
    ;password=123          # (default is no password)

    [program:openvpn]
    user=root
    # --auth-user-pass configs/openvpn.ovpn.auth (account\npassword)
    command=openvpn --auth-nocache --config configs/openvpn.ovpn --askpass configs/openvpn.ovpn.pass
    autostart=true
    autorestart=true
    stdout_logfile=logs/openvpn-client.log
    stderr_logfile=logs/openvpn-client.error

    [program:socks5_server]
    command=target/main server --addr=:1090
    autostart=true
    autorestart=true
    stdout_logfile=logs/socks5_server.log
    stderr_logfile=logs/socks5_server.error

    [program:socat_tcp-8000]
    command=socat TCP-LISTEN:8000,fork TCP:192.168.255.1:8000
    autostart=true
    autorestart=true
    stdout_logfile=logs/socat_tcp-8000.log
    stderr_logfile=logs/socat_tcp-8000.error

    [program:ssh-socks5]
    command=ssh-socks5.sh=configs/ssh.conf ssh-socks5.sh remote_host :1081
    autostart=true
    autorestart=true
    stdout_logfile=logs/ssh-socks5.log
    stderr_logfile=logs/ssh-socks5.error

    [program:file_server]
    command=target/main file_server --addr=:1099 --mount=./data/site:/site --mount=./logs:/logs
    autostart=true
    autorestart=true
    stdout_logfile=logs/file_server.log
    stderr_logfile=logs/file_server.error

supervisor_ssh: |
    # path: /apps/configs/supervisor.ini

    [program:socks5_ssh]
    command=target/main, ssh, -config=configs/prod.yaml, -addr=127.0.0.1:1080
    autostart=true
    autorestart=true
    stdout_logfile=logs/socks5_ssh.log
    stderr_logfile=logs/socks5_ssh.error

    [program:file_server]
    command=target/main file_server --addr=:1089
    autostart=true
    autorestart=true
    stdout_logfile=logs/file_server.log
    stderr_logfile=logs/file_server.error

ssh_config: |
    # path: configs/ssh.conf

    Host remote_host
        #ProxyJump host01,host02
        #ProxyCommand  nc -X 5 -x 127.0.0.1:1090 %h
        HostName 127.0.0.1
        User     account
        Port     22
        IdentityFile       configs/account.ssh-ed25519 # ~/.ssh/id_rsa
        UserKnownHostsFile configs/ssh-known_hosts     # ~/.ssh/known_hosts

        LogLevel              INFO
        Compression           yes
        TCPKeepAlive          yes
        ServerAliveInterval   5
        ServerAliveCountMax   3
        ConnectTimeout        10
        ExitOnForwardFailure  yes

        #RemoteCommand cd /path/to/project && bash
        #RemoteCommand HISTFILE='' bash --login
        #RequestTTY    yes
