app_name: socks5-proxy
app_version: 1.0.1
authors: ["d2jvkpn <d2jvkpn@noreply.local>"]
repository: git@github.com:d2jvkpn/socks5-proxy.git
image_name: socks5-proxy

ssh_proxy: |
  ##### location: configs/local.yaml

  ssh:
    ssh_host: remote_host
    ssh_port: 22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts
    socks5_user: hello
    socks5_password: world

  noauth:
    ssh_host: remote_host
    ssh_port: 22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts

socks5_proxy: |
    ##### location: configs/ssh.conf

    Host remote_host
        # ProxyJump another_host
        # ProxyCommand  nc -X 5 -x 127.0.0.1:1090 %h
        HostName 127.0.0.1
        User account
        Port 22
        IdentityFile configs/ssh.key # ~/.ssh/id_rsa
        UserKnownHostsFile configs/known_hosts # ~/.ssh/known_hosts
        LogLevel    INFO
        Compression yes
        ServerAliveInterval 5
        ServerAliveCountMax 3
        ExitOnForwardFailure yes
