services:
  socks5_ssh:
    image: ${IMAGE_Name}:${IMAGE_Tag}
    restart: always
    labels: { autoheal: true } # work with willfarrell/autoheal
    healthcheck:
      # --connect-timeout 2 --fail
      test: ["CMD", "curl", "-X", "OPTIONS", "-I", "-x", "socks5h://127.0.0.1:${SOCKS5_Port}", "http://remote_host:80"]
      start_period: 5s
      interval: 15s
      timeout: 3s
      retries: 3
    network_mode: host
    #extra_hosts:
    #- "hostv4=162.242.195.82"
    #- "hostv6=::1"
    user: "${USER_UID}:${USER_GID}"
    container_name: socks5-ssh
    volumes:
    - ./configs/:/apps/configs:ro
    environment: { TZ: Asia/Shanghai }
    working_dir: /apps
    command: [./target/main, ssh, -config=configs/prod.yaml, -addr=127.0.0.1:${SOCKS5_Port}]

  autoheal:
    image: willfarrell/autoheal
    restart: always
    network_mode: host
    # networks: ["net"]
    container_name: autoheal
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_INTERVAL: 5
      AUTOHEAL_START_PERIOD: 0
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 5
      AUTOHEAL_ONLY_MONITOR_RUNNING: false
      CURL_TIMEOUT: 5
      WEBHOOK_URL: ""
